# Generated by Django 4.2.7 on 2024-01-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_auto_20231220_1629"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
